mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
...



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'))
]

# Эти строки — в самый конец файла:
if settings.DEBUG:
    urlpatterns += static(
     settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
     )

mysite/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
]

mysite/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField("group name", max_length=200)
    slug = models.SlugField(unique=True, verbose_name='URL', max_length=20)
    describtion = models.TextField("Describtion"
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    poem = models.TextField()
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='groups',
        blank=True,
        null=True
        )
    image = models.ImageField( 'Картинка',upload_to='posts/', blank=True)

mysite/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    model = Post
    fields = ('text','group', 'img',)

mysite/posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Post, Group
# Create your views here.


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.order_by('-pub_date')
    context = {
        'title': "Посты",
        "names": ['Лев', "Игорь", "Григорий"],
        'text': 'Последние обновления on site',
        'posts': posts,
        } 
    
    return render(request, template, context)


def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект 
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
        'title': "Вл"}
    return render(request, 'posts/group_list.html', context)

mysite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
 <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="static/image/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->

   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

   {% block title %} пределяется из шаблонов {% endblock %}
  </head>
  <body>
    {% block header %}
      {% include 'includes/header.html' %}
    {% endblock %}
    <main>
      {% block content %}
        определяется из шаблонов
      {% endblock %}
    </main>
    {% block footer %}
      {% include 'includes/footer.html' %}
    {% endblock %}
  </body>
</html>

mysite/templates/includes/footer.html
<footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>
    </footer>

mysite/templates/includes/header.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>

    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="static/image/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Последние обновления на сайте</title>
  </head>
  <body>
    <header>

      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="index.html">
           <img src="{% static 'image/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
        </div>
      </nav>
    </header>

mysite/templates/posts/group_list.html
{% extends 'base.html' %}

{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
  <article>
    <p> {{group.title}} </p>
    {% if posts %}
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <p style="background: lightskyblue; color: rgb(0, 0, 255)"><b>"{{ post.poem }}"</b></p>
        <hr>
      {% endfor %}
    </article>
    <!-- под последним постом нет линии -->
    <a class="navbar-brand" href="{% url 'posts:index' %}">Posts</a>
    {% endif %}
  </div>
{% endblock %}     

mysite/templates/posts/index.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% load static %}

{%block icon%}
<link rel="icon" href="{% static 'img/mail.png' %}" type="image">
{%endblock%}

{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1> {{text}} </h1>
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}

      </ul>
      <p>{{ post.text }}</p>
      <p style="background: lightskyblue; color: rgb(0, 0, 255)"><b>"{{ post.poem }}"</b></p>    

      <hr>
    {% endfor %} 
        <!-- под последним постом нет линии -->
    {% for char in names %}
      {% if forloop.first %}
        <p>Начало цикла</p>
      {% endif %}
        <ul style="color: rgb(255, 0, 0)">
          <li>
        <p><b>{{ char }}</b></p></li>
          </ul>
    {# forloop хранит счётчик цикла и может определять разные состояния счётчика #}
      {% if forloop.last %}
        <p>Конец цикла</p>
      {% endif %}
      {% empty %}
        <p>Если цикл пуст</p>
    {% endfor %}    
 
    </div>  
{% endblock %}

mysite/templates/posts/spiski.html
{% extends 'base.html' %}
 {% block title %}
    <title>
            {% if text == 'Главная Страница' %}
                   Вы на главной странице.
            {% elif text == 'Вложенная страница' %}
                   Вы в одном клике от главной страницы!
            {% else %}
                   Мы понятия не имеем, где вы!
            {% endif %}
    </title>
 {% endblock %}

 {% block content %}
      <div class="container py-5">
        <h1>Последние обновления на сайте</h1>

        <!-- под последним постом нет линии -->


<style>
  b {color:red}

</style>


      {% for i in names %}
      {% if forloop.first %}
        <p>Начало цикла</p>
      {% endif %}
   <b> <ul> <li>{{ i }}</li> </ul> </b>
      {# forloop хранит счётчик цикла и может определять разные состояния счётчика #}
      {% if forloop.last %}
        <p>Конец цикла</p>
      {% endif %}
      {% empty %}
      <p>Если цикл пуст</p>
      {% endfor %}

      </div>
  {% endblock %}